apiVersion: v1
kind: Service
metadata:
  name: neolaas-headless
  namespace: infra
spec:
  clusterIP: None  # Headless service
  selector:
    app: neolaas
  ports:
    - port: 9000
      name: kameo
      protocol: TCP
    - port: 8080
      name: http
      protocol: TCP
